import type { Metadata } from "next";
import "./globals.css";
import { fraunces, manrope } from "./font";

export const metadata: Metadata = {
  title: "Workit Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fraunces.variable} ${manrope.variable} w-full h-full`}>{children}</body>
    </html>
  );
}
